[tool.poetry]
name = "sborka-saita"
version = "0.1.0"
description = ""
authors = ["Arina <arinafedor23@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
